// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDqGntbIaxlUJZFLfatUxdBXpVA3pqQ1A',
    appId: '1:989286033095:web:4eefdf4d6105966bd980e2',
    messagingSenderId: '989286033095',
    projectId: 'dental-clinic-app-busaru',
    authDomain: 'dental-clinic-app-busaru.firebaseapp.com',
    storageBucket: 'dental-clinic-app-busaru.appspot.com',
    measurementId: 'G-SV75XK122J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqILRN52JJ0Rc4_5D6jwJZlnn31AEtxSI',
    appId: '1:989286033095:android:097d3c799b17a3c7d980e2',
    messagingSenderId: '989286033095',
    projectId: 'dental-clinic-app-busaru',
    storageBucket: 'dental-clinic-app-busaru.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTdvQS8u5OEMGUgj7_nyjPsGWw7eupO_4',
    appId: '1:989286033095:ios:5f3d80be34017c5ad980e2',
    messagingSenderId: '989286033095',
    projectId: 'dental-clinic-app-busaru',
    storageBucket: 'dental-clinic-app-busaru.appspot.com',
    iosClientId: '989286033095-bug5k2o4u388veontroiq5fmjbrbafao.apps.googleusercontent.com',
    iosBundleId: 'com.example.dentalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTdvQS8u5OEMGUgj7_nyjPsGWw7eupO_4',
    appId: '1:989286033095:ios:5f3d80be34017c5ad980e2',
    messagingSenderId: '989286033095',
    projectId: 'dental-clinic-app-busaru',
    storageBucket: 'dental-clinic-app-busaru.appspot.com',
    iosClientId: '989286033095-bug5k2o4u388veontroiq5fmjbrbafao.apps.googleusercontent.com',
    iosBundleId: 'com.example.dentalapp',
  );
}
